export const CONTRACT_CATALOG = [
  { id: 'rat-extermination', name: 'Rat Extermination', description: 'Clear the cellars before the infestation reaches the market.', tier: 'Common', region: 'frontier', faction: 'crown', enemy: 'goblins', minGuildLevel: 1, durationSeconds: 60, requiredPower: 10, rewardGold: 20, rewardReputation: 1, failureGold: 5, rewardMaterials: 1 },
  { id: 'supply-escort', name: 'Supply Escort', description: 'Protect a wagon train crossing the frontier road.', tier: 'Common', region: 'frontier', faction: 'merchants', enemy: 'bandits', minGuildLevel: 2, durationSeconds: 120, requiredPower: 20, rewardGold: 40, rewardReputation: 2, failureGold: 10, rewardMaterials: 2 },
  { id: 'goblin-cleanup', name: 'Goblin Cleanup', description: 'Drive a growing goblin warband away from a farming village.', tier: 'Common', region: 'frontier', faction: 'rangers', enemy: 'goblins', minGuildLevel: 3, durationSeconds: 180, requiredPower: 30, rewardGold: 60, rewardReputation: 3, failureGold: 15, rewardMaterials: 3 },
  { id: 'ogre-toll-road', name: 'Ogre Toll Road', description: 'End the ogre toll that has strangled the frontier trade route.', tier: 'Uncommon', region: 'frontier', faction: 'merchants', enemy: 'bandits', minGuildLevel: 4, minReputation: 6, durationSeconds: 240, requiredPower: 42, rewardGold: 95, rewardReputation: 5, failureGold: 24, rewardMaterials: 4, rewardItem: 'guildmail' },
  { id: 'greenwood-rescue', name: 'Greenwood Rescue', description: 'Find missing rangers before the forest closes around them.', tier: 'Elite', region: 'greenwood', faction: 'rangers', enemy: 'spiders', minGuildLevel: 2, minReputation: 8, durationSeconds: 300, requiredPower: 55, rewardGold: 140, rewardReputation: 6, failureGold: 35, rewardMaterials: 5, rewardItem: 'hunter-bow' },
  { id: 'bandit-hideout', name: 'Bandit Hideout', description: 'Strike the hideout and recover stolen trade charters.', tier: 'Elite', region: 'frontier', faction: 'crown', enemy: 'bandits', minGuildLevel: 4, minReputation: 14, durationSeconds: 420, requiredPower: 75, rewardGold: 250, rewardReputation: 8, failureGold: 60, rewardMaterials: 7, rewardItem: 'iron-sword' },
  { id: 'ashen-mine', name: 'Ashen Mine Survey', description: 'Map a mine where the stone itself has begun to burn.', tier: 'Elite', region: 'ashen-mountains', faction: 'foundries', enemy: 'elementals', minGuildLevel: 4, minReputation: 20, durationSeconds: 540, requiredPower: 105, rewardGold: 360, rewardReputation: 10, failureGold: 85, rewardMaterials: 10, rewardItem: 'tower-shield' },
  { id: 'ogre-hunt', name: 'Ogre Hunt', description: 'Bring down the mountain ogre before it reaches the lowlands.', tier: 'Elite', region: 'ashen-mountains', faction: 'rangers', enemy: 'elementals', minGuildLevel: 5, minReputation: 28, durationSeconds: 720, requiredPower: 120, rewardGold: 400, rewardReputation: 12, failureGold: 100, rewardMaterials: 12, rewardItem: 'ember-charm' },
  { id: 'old-kingdom-vault', name: 'Old Kingdom Vault', description: 'Open a sealed vault beneath the fallen capital.', tier: 'Legendary', region: 'old-kingdom', faction: 'mages', enemy: 'undead', minGuildLevel: 6, minReputation: 40, durationSeconds: 900, requiredPower: 175, rewardGold: 850, rewardReputation: 18, failureGold: 160, rewardMaterials: 18, rewardItem: 'dragon-signet' },
  { id: 'dragon-expedition', name: 'Dragon Expedition', description: 'Face the dragon beneath the mountain and end its long shadow.', tier: 'Legendary', region: 'forbidden-depths', faction: 'crown', enemy: 'dragons', minGuildLevel: 9, minReputation: 70, durationSeconds: 1200, requiredPower: 250, rewardGold: 1500, rewardReputation: 30, failureGold: 300, rewardMaterials: 30, rewardItem: 'dragon-signet', boss: true }
];

export function catalogContract(id) {
  return CONTRACT_CATALOG.find(contract => contract.id === id) || null;
}
